### ISSUE TITLE
[PE-D][Tester A] Grammatical error in listing steps/ingredients

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F13-1/tp#68]
![image.png](https://raw.githubusercontent.com/ArtemiszenN/ped/main/files/2baffeef-f4b3-4dc4-a373-5152fcf75a81.png)

![image.png](https://raw.githubusercontent.com/ArtemiszenN/ped/main/files/85a830db-0c50-41c4-845c-4dc60b49e345.png)

When there is only 1 step in the list, the message provided is grammatically wrong. Also applies to ingredients provided.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ArtemiszenN/ped#1

**Comment by Aung-Phone-Naing** [comment]
Just have a separate string for when there is only 1 item in the list.
