### ISSUE TITLE
[PE-D][Tester A] Unhandled special characters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-F13-1/tp#70]
![image.png](https://raw.githubusercontent.com/ArtemiszenN/ped/main/files/15de7b44-a818-449c-a454-2787b56116c6.png)

Unhandled characters prevent saving

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ArtemiszenN/ped#3

**Comment by YatPang** [comment]
Issue resolved by removing recipe name from save file name.
NFA.
