### ISSUE TITLE
[PE-D][Tester C] Add/delete step/ingredient function

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F13-1/tp#73]
Having features for addstep/ingredients, deletestep/ingredients would be desirable. Currently, if the user wants to change the number of steps or ingredients that they have in their recipe, they must delete the whole recipe and rewrite it from scratch. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: honglinshang/ped#6

**Comment by Aung-Phone-Naing** [comment]
@LimHongYao would be good to have if you can implement in time.

**Comment by liuziyang020319** [comment]
Solved already
