### ISSUE TITLE
[PE-D][Tester A] Able to add recipe with 0 ingredients

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-F13-1/tp#74]
![image.png](https://raw.githubusercontent.com/ArtemiszenN/ped/main/files/7ea03a18-6d5e-4c29-bf57-4e19227d3065.png)

Not allowed unless using this method. Also works for i/,,, or any number of commas 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ArtemiszenN/ped#4

**Comment by Aung-Phone-Naing** [comment]
@LimHongYao can check the strings of the ingredients before assigning to recipe to filter for such bugs where there are no ingredients in the recipe.

**Comment by LimHongYao** [comment]
modify behaviour: allow for ingredientsList to be 0, in future implement addition/removal of ingredients

**Comment by LimHongYao** [comment]
immediate fix created, additional fix pending
