### ISSUE TITLE
[PE-D][Tester C] Link for jar not included in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F13-1/tp#76]
(under Quick Start)

![Screenshot 2023-03-31 at 5.02.23 PM.png](https://raw.githubusercontent.com/honglinshang/ped/main/files/d3a94386-81eb-459c-ad74-265bcde018d1.png)

-------------
Labels: `type.DocumentationBug` `severity.High`
original: honglinshang/ped#8

**Comment by Aung-Phone-Naing** [comment]
Issue has been fixed in the latest PR #106
