### ISSUE TITLE
[PE-D][Tester D]  Index Checking for Edit ingredient only checks > n and not 0 or below

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F13-1/tp#81]
Similar to edit step, the same minor bug occurs.

![image.png](https://raw.githubusercontent.com/shawntangy/ped/main/files/5849710b-64db-4d61-a114-eac100c05f5f.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: shawntangy/ped#3

**Comment by Aung-Phone-Naing** [comment]
@LimHongYao same error as #77 but this time round its for ingredients.
