### ISSUE TITLE
[PE-D][Tester A] Grammatical error when viewing some dishes with a flavor that starts with a vowel

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F13-1/tp#87]
![image.png](https://raw.githubusercontent.com/ArtemiszenN/ped/main/files/c880271b-6cff-4e8f-86b6-0c9b66b009b8.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ArtemiszenN/ped#8

**Comment by Aung-Phone-Naing** [comment]
Bug fixed by removing "a" in PR #106.
