### ISSUE TITLE
[PE-D][Tester A] View by name missing functionality

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F13-1/tp#91]
![image.png](https://raw.githubusercontent.com/ArtemiszenN/ped/main/files/b5b16851-7be4-4368-80df-c05faf57abcd.png)

Shown in help section but not UG

![image.png](https://raw.githubusercontent.com/ArtemiszenN/ped/main/files/418ebad6-22a5-4d8f-9522-858dea707a8b.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: ArtemiszenN/ped#10

**Comment by Aung-Phone-Naing** [comment]
@LimHongYao Same issue as #67.
